exports.generateWeeklyReportHtml = (client, completedTasks, pendingTasks, campaigns, comms, meetings, escalations, settings) => {
  const companyName = client.company_name;
  
  const includeCampaigns = settings?.include_campaigns !== false;
  const includeTasks = settings?.include_tasks !== false;
  const includeComms = settings?.include_communications !== false;
  
  // Section 1: Executive Summary / Intro
  let html = `
    <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; max-width: 650px; margin: 0 auto; padding: 0; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
      
      <!-- Header Area -->
      <div style="background-color: #4f46e5; padding: 40px 30px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 700; letter-spacing: -0.5px;">Weekly Performance Report</h1>
        <p style="color: #c7d2fe; margin-top: 10px; margin-bottom: 0; font-size: 16px;">Prepared for <strong>${companyName}</strong></p>
      </div>

      <div style="padding: 30px;">
        <p style="font-size: 15px; line-height: 1.6; color: #475569; margin-top: 0;">
          Hi Team,<br><br>Here is a comprehensive breakdown of the work we have completed for your brand over the last 7 days, our current campaign metrics, and what we have planned for the week ahead.
        </p>
  `;

  // Section 2: Campaign Metrics
  if (includeCampaigns && campaigns && campaigns.length > 0) {
    let campaignsHtml = campaigns.map(c => `
      <li style="margin-bottom: 10px;">
        <strong>${c.campaign_name}</strong><br/>
        Spend: ₹${c.spend_inr?.toLocaleString() || 0} | 
        Clicks: ${c.clicks?.toLocaleString() || 0} | 
        Leads: ${c.leads_conversions?.toLocaleString() || 0} | 
        CPL: ₹${c.cost_per_lead_inr?.toLocaleString() || 0}
      </li>
    `).join('');

    html += `
      <h3 style="color: #1e293b; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px;">Active Campaign Performance</h3>
      <ul style="padding-left: 20px; color: #475569;">${campaignsHtml}</ul>
    `;
  }

  if (includeTasks) {
    // Section 3: Completed Work
    let tasksHtml = (completedTasks && completedTasks.length > 0) 
      ? completedTasks.map(t => `<li style="margin-bottom: 8px;"><strong>${t.title}</strong> - ${t.status}</li>`).join('') 
      : '<li>No tasks completed this week.</li>';

    html += `
      <h3 style="color: #1e293b; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px;">Completed Deliverables</h3>
      <ul style="padding-left: 20px; color: #475569;">${tasksHtml}</ul>
    `;

    // Section 4: Upcoming / Pending
    let pendingHtml = (pendingTasks && pendingTasks.length > 0) 
      ? pendingTasks.map(t => `<li style="margin-bottom: 8px;"><strong>${t.title}</strong> - Scheduled</li>`).join('') 
      : '<li>No pending tasks.</li>';

    html += `
      <h3 style="color: #1e293b; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px;">Goals for Next Week</h3>
      <ul style="padding-left: 20px; color: #475569;">${pendingHtml}</ul>
    `;
  }

  // Section 5: Meetings & Comms Summary
  let mtgHtml = '';
  if (includeComms && ((meetings && meetings.length > 0) || (escalations && escalations.length > 0))) {
    mtgHtml += `<h3 style="color: #1e293b; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px;">Communications & Updates</h3><ul style="padding-left: 20px; color: #475569;">`;
    
    if (meetings && meetings.length > 0) {
      mtgHtml += meetings.map(m => `<li>Meeting Held: ${m.title} on ${new Date(m.meeting_date).toLocaleDateString()}</li>`).join('');
    }
    if (escalations && escalations.length > 0) {
      mtgHtml += escalations.map(e => `<li>Issue Resolved: ${e.title}</li>`).join('');
    }
    mtgHtml += `</ul>`;
    html += mtgHtml;
  }

  // Footer
  html += `
      </div>
      <div style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
        <p style="margin: 0; color: #94a3b8; font-size: 12px;">This automated report was generated by the RDS Dashboard.</p>
      </div>
    </div>
  `;

  return html;
};
